//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeraziDevEx.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Terazi1Aktivite {
            get {
                return ((bool)(this["Terazi1Aktivite"]));
            }
            set {
                this["Terazi1Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Terazi2Aktivite {
            get {
                return ((bool)(this["Terazi2Aktivite"]));
            }
            set {
                this["Terazi2Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Terazi3Aktivite {
            get {
                return ((bool)(this["Terazi3Aktivite"]));
            }
            set {
                this["Terazi3Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Terazi4Aktivite {
            get {
                return ((bool)(this["Terazi4Aktivite"]));
            }
            set {
                this["Terazi4Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Terazi5Aktivite {
            get {
                return ((bool)(this["Terazi5Aktivite"]));
            }
            set {
                this["Terazi5Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 1")]
        public string TeraziIsim1 {
            get {
                return ((string)(this["TeraziIsim1"]));
            }
            set {
                this["TeraziIsim1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 2")]
        public string TeraziIsim2 {
            get {
                return ((string)(this["TeraziIsim2"]));
            }
            set {
                this["TeraziIsim2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 3")]
        public string TeraziIsim3 {
            get {
                return ((string)(this["TeraziIsim3"]));
            }
            set {
                this["TeraziIsim3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 4")]
        public string TeraziIsim4 {
            get {
                return ((string)(this["TeraziIsim4"]));
            }
            set {
                this["TeraziIsim4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 5")]
        public string TeraziIsim5 {
            get {
                return ((string)(this["TeraziIsim5"]));
            }
            set {
                this["TeraziIsim5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom1 {
            get {
                return ((string)(this["TeraziCom1"]));
            }
            set {
                this["TeraziCom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom2 {
            get {
                return ((string)(this["TeraziCom2"]));
            }
            set {
                this["TeraziCom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom3 {
            get {
                return ((string)(this["TeraziCom3"]));
            }
            set {
                this["TeraziCom3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom4 {
            get {
                return ((string)(this["TeraziCom4"]));
            }
            set {
                this["TeraziCom4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom5 {
            get {
                return ((string)(this["TeraziCom5"]));
            }
            set {
                this["TeraziCom5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TeraziCom6 {
            get {
                return ((string)(this["TeraziCom6"]));
            }
            set {
                this["TeraziCom6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Terazi 6")]
        public string TeraziIsim6 {
            get {
                return ((string)(this["TeraziIsim6"]));
            }
            set {
                this["TeraziIsim6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Terazi6Aktivite {
            get {
                return ((bool)(this["Terazi6Aktivite"]));
            }
            set {
                this["Terazi6Aktivite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B99B6GC;Initial Catalog=Terazi;Integrated Security=False;User" +
            " ID=genesis;Password=genesis;Connect Timeout=15;Encrypt=False;TrustServerCertifi" +
            "cate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string conString {
            get {
                return ((string)(this["conString"]));
            }
            set {
                this["conString"] = value;
            }
        }
    }
}
